"""Add contacts and devices

Revision ID: 1d9a18f7506b
Revises: 69aa2b7e92a8
Create Date: 2026-09-02 20:22:52.579324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d9a18f7506b'
down_revision: Union[str, Sequence[str], None] = '69aa2b7e92a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('device_contact_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone_numbers', sa.JSON(), nullable=True),
    sa.Column('emails', sa.JSON(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('addresses', sa.JSON(), nullable=True),
    sa.Column('birthday', sa.String(), nullable=True),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_device_id', sa.String(), nullable=True),
    sa.Column('updated_by_device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_deleted_at'), 'contacts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_contacts_device_contact_id'), 'contacts', ['device_contact_id'], unique=False)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_index(op.f('ix_contacts_name'), 'contacts', ['name'], unique=False)
    op.create_index(op.f('ix_contacts_owner_user_id'), 'contacts', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_contacts_sync_version'), 'contacts', ['sync_version'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('device_identifier', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('last_sync_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'device_identifier', name='uq_device_user_identifier')
    )
    op.create_index(op.f('ix_devices_device_identifier'), 'devices', ['device_identifier'], unique=False)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_owner_user_id'), 'devices', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_owner_user_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_identifier'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_contacts_sync_version'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_owner_user_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_device_contact_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_deleted_at'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
